language: java
sudo: false
install: true

jdk:
- openjdk15

services:
  - docker

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file:
      - build/libs/*-all.jar
      - jattach-debug-plugin/build/libs/*
      - api/build/libs/*
    skip_cleanup: true
    name: $TRAVIS_TAG
    on:
      tags: true
  - provider: script
    script: bash -c 'chmod +x gradlew && ./gradlew api:bintrayUpload'
    on:
      tags: true
  - provider: pages
    skip-cleanup: true
    local-dir: api/build/docs/javadoc
    github-token: $GITHUB_TOKEN
    on:
      branch: master
  - provider: script
    script: bash docker_push.sh

script:
- chmod +x gradlew
- env "TAG=$TRAVIS_TAG" ./gradlew ci
